//https://projecteuler.net/problem=2
//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

public class Problem002 {
	public static void main(String[] args) {
		System.out.println(calculation());
		
		
	}

	public static int calculation() {
		int sum = 0;
		for(int i = 0; i < 34; i++){
			if(fib(i) % 2 == 0) sum+= fib(i);
		}
		return sum;
	}

	public static int fib(int n) {
		  if (n == 0) {
		    return 0;
		  }
		  int a = 1;
		  int b = 1;
		  for (int i = 3; i <= n; i++) {
		    int c = a + b;
		    a = b;
		    b = c;
		  }
		  return b;
		}
}
